version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: circleci/node:14.9
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test

workflows:
  main:
    jobs:
      - test