version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

executors:
  default:
    docker:
      - image: cimg/node:14.17

jobs:
  test:
    executor: default
    steps:
      - checkout
      - run: yarn install
      - run: yarn jest
  deploy:
    executor: default
    steps:
      - checkout
      - run: yarn run build
      - aws-s3/copy:
          from: dist
          to: 's3://circleci_tester'
          overwrite: true

workflows:
  main:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: main
