version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

executors:
  default:
    docker:
      - image: cimg/node:14.17

commands:
  yarn_install:
    steps:
      - restore_cache:
          key: yarn-deps-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: yarn-deps-cache-{{ checksum "package.json" }}
          paths:
              - node_modules

jobs:
  test:
    executor: default
    steps:
      - checkout
      - yarn_install
      - run: yarn jest
  deploy:
    executor: default
    steps:
      - checkout
      - yarn_install
      - run: yarn run build
      - aws-s3/copy:
          from: ./dist
          to: 's3://circleci-tester'

workflows:
  main:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - test